complete_task:
  fields:
    task_id:
      required: true
      selector:
        text:
    member_id:
      required: false
      selector:
        text:

skip_task:
  fields:
    task_id:
      required: true
      selector:
        text:

toggle_subtask:
  fields:
    task_id:
      required: true
      selector:
        text:
    subtask_id:
      required: true
      selector:
        text:
